PACKAGE_NAME="yeetmouse"
PACKAGE_VERSION="#MODULE_VERSION#"
AUTOINSTALL="yes"
MAKE="KERNELDIR=/lib/modules/${kernelver}/build make driver"

BUILT_MODULE_NAME="yeetmouse"

BUILT_MODULE_LOCATION="driver"

DEST_MODULE_LOCATION="/kernel/drivers/hid"